name: Setup app
runs:
  using: composite
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "name=dir::$(yarn cache dir)" >> $GITHUB_OUTPUT
      shell: bash

    - uses: actions/cache@v3
      id: yarn-cache
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: Install
      run: yarn
      shell: bash
