name: Setup app
runs:
  using: composite
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'yarn'

    - name: Install
      run: yarn
      shell: bash
