name: Update exchange rates
on:
  schedule:
    - cron: '* * * * *'

jobs:
  updateExchangeRates:
    runs-on: ubuntu-latest
    steps:
      - name: Update exchange rates
        run: |-
          curl -X POST https://budget.saltares.com/api/con/updateExchangeRates?CRON_API_KEY=${{ secrets.CRON_API_KEY }}
