name: Update exchange rates
on:
  schedule:
    - cron: '30 12 * * *' # at 12.30 every day

jobs:
  updateExchangeRates:
    runs-on: ubuntu-latest
    steps:
      - name: Update exchange rates
        run: |-
          curl -X POST https://finlight.saltares.com/api/cron/updateExchangeRates?CRON_API_KEY=${{ secrets.CRON_API_KEY }}
